"""initial schema

Revision ID: 0208f1059d4e
Revises: 
Create Date: 2026-05-19 22:12:53.315412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0208f1059d4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_up', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('last_latency', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('last_status_code', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('failure_count', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('last_checked', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'last_checked')
    op.drop_column('services', 'failure_count')
    op.drop_column('services', 'last_status_code')
    op.drop_column('services', 'last_latency')
    op.drop_column('services', 'is_up')
    # ### end Alembic commands ###
