"""database updated indexes and proper ist time is added in the system

Revision ID: 559eaf1c5612
Revises: cff6b59fc4d5
Create Date: 2026-05-26 00:40:13.612717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559eaf1c5612'
down_revision: Union[str, Sequence[str], None] = 'cff6b59fc4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_services_created_at'), 'services', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_created_at'), table_name='services')
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    # ### end Alembic commands ###
